version: 2
updates:
  # .NET NuGet packages - Patch and Minor updates (grouped weekly)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    groups:
      patch-minor-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    commit-message:
      prefix: "deps"
      include: "scope"

  # .NET NuGet packages - Major updates (grouped weekly, separate PRs)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 3
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "deps(major)"
      include: "scope"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
